FGBook/config/routes.rb
Rails.application.routes.draw do
  resources :books
  resources :users

	resource :confirmation, only: [:show]
	resource :user_sessions, only: [:create, :new, :destroy]

	resources :books do
		resources :reviews, only: [:create, :update], module: :books
	end

  root 'home#index'

end

FGBook/app/models/book.rb
class Book < ActiveRecord::Base
	has_many :reviews, dependent: :destroy
	belongs_to :user

	def complete_name
		"#{title}, #{author}"
	end
end

FGBook/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :book, counter_cache: true

	validates_uniqueness_of :user_id, scope: :book_id
	validates_presence_of :points, :user_id, :book_id
	validates_inclusion_of :points, in: POINTS
end

FGBook/app/models/user.rb
class User < ActiveRecord::Base
	EMAIL_REGEXP = /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/

	has_many :books, dependent: :destroy
  has_many :reviews, dependent: :destroy

	scope :confirmed, -> { where.not(confirmed_at: nil) }
	
	validates_presence_of :email, :full_name, :locatino
	validates_format_of :email, with: EMAIL_REGEXP

	has_secure_password

	before_create do |user|
		user.confirmation_token = SecureRandom.urlsafe_base64
	end

	def confirm!
		return if confirmed?

		self.confirmed_at = Time.current
		self.confirmation_token = ''
		save!
	end

	def confirmed?
		confirmed_at.present?
	end

	def self.authenticate(email, password)
		user = confirmed.find_by(email: email)
		if user.present?
			user.authenticate(password)
		end
	end
end

FGBook/app/models/user_session.rb
class UserSession
	include ActiveModel::Model

	attr_accessor :email, :password
	validates_presence_of :email, :password

	def initialize(session, attributes={})
		@session = session
		@email = attributes[:email]
		@password = attributes[:password]
	end

	def authenticate!
		user= User.authenticate(@email, @password)

		if user.present?
			store(user)
		else
			errors.add(:base, :invalid_login)
			false
		end
	end

	def store(user)
		@session[:user_id] = user.id
	end

	def current_user
		User.find(@session[:user_id])
	end

	def user_signed_in?
		@session[:user_id].present?
	end

	def destroy
		@session[:user_id] = nil
	end
end

FGBook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	delegate :current_user, :user_signed_in?, to: :user_session
	helper_method :current_user, :user_signed_in?
	
	def user_session
		UserSession.new(session)
	end

	def require_authentication
		unless user_signed_in?
			redirect_to new_user_sessions_path, alert: t('flash.alert.needs_login')
		end
	end

	def require_no_authentication
		if user_signed_in?
			redirect_to root_path, notice: t('flash.notice.already_logged_in')
		end
	end
end

FGBook/app/controllers/books.rb
Books::ReviewsController

FGBook/app/controllers/books/reviews_controller.rb
class Books::ReviewsController < ApplicationController
  before_filter :require_authentication

  def create
    review = book.reviews.
      find_or_initialize_by(user_id: current_user.id)

    review.update!(review_params)

    head :ok
  end

  def update
    create
  end

  private

  def book
    @book ||= Book.find(params[:book_id])
  end

  def review_params
    params.
      require(:review).permit(:points)
  end
end

FGBook/app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :set_book, only: [:show]
  before_action :set_users_book, only: [:edit, :update, :destroy]
	before_action :require_authentication, only: [:show, :edit, :create, :update, :destroy]

  def index
    @books = Book.all
  end

  def show
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def create
    @book = Book.new(book_params)

      if @book.save
        redirect_to @book, notice: t('flash.notice.book_created')
      else
        render :new
      end
  end

  def update
      if @book.update(book_params)
        redirect_to @book, notice: t('flash.notice.book_updated')
      else
        render :edit 
      end
  end

  def destroy
    @book.destroy
    redirect_to books_url  
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:title, :author, :price, :telephone, :description)
    end
		
		def set_users_books
			@book = current_user.books.find(params[:id])
		end
end

FGBook/app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController
	def show
		user = User.find_by(confirmation_token: params[:token])

		if user.present?
			user.confirm!
			redirect_to user, notice: I18n.t('confirmations.success')
		else
			redirect_to root_path
		end
	end
end

FGBook/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@books = Book.take(3)
	end
end

FGBook/app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
	def new
		@user_session = UserSession.new(session)
	end

	def create
		@user_session = UserSession.new(session, params[:user_session])

		if @user_session.authenticate!		
			redirect_to root_path, notice: t('flash.notice.signed_in')
		else
			render :new
		end
	end

	def destroy
		user_session.destroy
		redirect_to root_path, notice: t('flash.notice.signed_out')
	end
end

FGBook/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_no_authentication, only: [:new, :create]
	before_action :require_authentication, only: :destroy
	before_action :can_change, only: [:edit, :update]


	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end
	
	def create
		@user = User.new(user_params)
		if @user.save
			Signup.confirm_email(@user).deliver

			redirect_to @user, notice: 'Cadastro criado com sucesso!'
		else
			render :new
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to @user, 
				notice: 'Cadastro atualizado com sucesso!'
		else
			render action: :edit
		end
	end

	private

	def user_params
		params.require(:user).permit(:email, :full_name, :locatino, :password, :password_confirmation)
	end
	
	def can_change
		unless user_signed_in? && current_user == user
			redirect_to user_path(params[:id])
		end
	end

	def user
		@user ||= User.find(params[:id])
	end
end

FGBook/app/helpers/application_helper.rb
module ApplicationHelper
	def error_tag(model, attribute)
		if model.errors.has_key? attribute
			content_tag(
				:div,
				model.errors[attribute].first,
				class: 'error_message'
			)
		end
	end
end

FGBook/app/helpers/books_helper.rb
module BooksHelper
	def belongs_to_user(book)
		user_signed_in? && book.user == current_user
	end
end

FGBook/app/views/books/_book.html.erb
     <article class="book">
        <h2><%= link_to book.title, book %></h2>
				<span class="created">
					<%= t '.owner_html', 

						when: l(book.created_at, format: :short) %>
				</span>
				<p>
					<span class="author">
						<%= link_to book.author, "https://www.google.com/#q=#{book.author}", target: :blank %>
					</span>
					<%= " — R$ #{book.price}; " %>
					<%= t '.telephone' %>
					<span class="telephone">
						<%= link_to  "#{book.telephone}", "https://www.google.com/#q=#{book.telephone}", target: :blank %>
					</span>	
				</p>
				<p><%= book.description %></p>
				<% if belongs_to_user(book) %>
					<ul>
						<li><%= link_to t('.edit'), edit_book_path(book) %></li>
						<li><%= link_to t('.destroy'), book_path(book), method: :delete, data: {confirm: t('dialogs.destroy')} %></li>
					</ul>
				<% end %>
			</article>

FGBook/app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br>
    <%= f.text_field :telephone %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

FGBook/app/views/books/_review.html.erb
<section class="review">
	<% if user_signed_in? %>
		<%= form_for [review.book, review] do |f| %>
			<% Review::POINTS.each do |point| %>
				<%= f.radio_button :points, point %>
				<%= f.label :points, point, value: point %>
			<% end %>
			
			<% f.submit %>
		<% end %>
	<% else %>
		<span class="login_required">
			<%= t('.login_to_review') %>
		</span>
	<% end %>
</section>

FGBook/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

FGBook/app/views/books/index.html.erb
<h1><%= t '.title' %></h1>

<%= render @books %>

FGBook/app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

FGBook/app/views/books/show.html.erb
<%= render @book %>

FGBook/app/views/home/index.html.erb
<h1>Livros recém postados</h1>

<ul>
	<% @books.each do |book| %>
		<li>
			<%= link_to "#{book.title}, #{book.author}", book %>
		</li>
	<% end %>
</ul>

FGBook/app/views/layouts/_user_navbar.html.erb
<nav>
	<ul>
		<li><%= link_to t('layout.new_book'), new_book_path %></li>
		<li><%= link_to t('layout.books'), books_path %></li>
		<li><%= link_to t('layout.my_profile'), user_path(current_user) %></li>
		<li><%= link_to t('layout.signout'), user_sessions_path, method: :delete %></li>
	</ul>
</nav>

FGBook/app/views/layouts/_visitor_navbar.html.erb
<nav>
	<ul>
		<li><%= link_to t('layout.books'), books_path %></li>
		<li><%= link_to t('layout.signup'), new_user_path %></li>
		<li><%= link_to t('layout.signin'), new_user_sessions_path %></li>
	</ul>
</nav>

FGBook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FGBook</title>
	<link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<div id="header-wrap">
			<h1><%= link_to "FGBook", root_path %></h1>
			<% if user_signed_in? %>
				<%= render 'layouts/user_navbar' %>
			<% else %>
				<%= render 'layouts/visitor_navbar' %>
			<% end %>
		</div>
	</header>

	<div id="content">
		<% if notice.present? %>
			<p id="notice"><%= notice %></p>
		<% end %>
		<% if alert.present? %>
			<p id="alert"><%= alert %></p>
		<% end %>

<%= yield %>

</body>
</html>

FGBook/app/views/signup/confirm_email.html.erb
<h1><%= t '.title' %></h1>
<p>
	<%= t '.body', full_name: @user.full_name %>
</p>
<p>
	<%= t '.confirm_link_html', link: link_to(@confirmation_link, @confirmation_link) %>
</p>
<p>
	<%= t '.thanks_html', link: link_to('FGBook', root_url) %>
</p>

FGBook/app/views/signup/confirm_email.text.erb
<%= t '.title' %>

<%= t '.body', full_name: @user.full_name %>
<%= t '.confirm_link_html', link: @confirmation_link %>

<%= t '.thanks_html', link: root_url %>

FGBook/app/views/user_sessions/new.html.erb
<h1><%= t '.title' %></h1>

<% if @user_session.errors.has_key? :base %>
	<div id="error_explanation">
		<%= @user_session.errors[:base].join(', ') %>
	</div>
<% end %>

<%= form_for @user_session do |f| %>
	<p>
		<%= f.label :email %>
		<%= f.text_field :email %>
		<%= error_tag @user_session, :email %>
	</p>
	<p>
		<%= f.label :password %>
		<%= f.password_field :password %>
		<%= error_tag @user_session, :password %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

<p><%= link_to t('.sign_up'), new_user_path %></p>

FGBook/app/views/users/_form.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
			<%= t 'general.form_error' %>
	</div>
<% end %>

<%= form_for @user do |f| %>
	<p>
		<%= f.label :full_name %>
		<%= f.text_field :full_name %>
		<%= error_tag @user, :full_name %>
	</p>
	<p>
		<%= f.label :locatino %>
		<%= f.text_field :locatino %>
		<%= error_tag @user, :locatino %>
	</p>
	<p>
		<%= f.label :email %>
		<%= f.text_field :email %>
		<%= error_tag @user, :email %>
	</p>
	<p>
		<%= f.label :password %>
		<%= f.password_field :password %>
		<%= error_tag @user, :password %>
	</p>
	<p>
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
		<%= error_tag @user, :password_confirmation %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

FGBook/app/views/users/edit.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

<% link_to t('links.back'), @user %>

FGBook/app/views/users/new.html.erb
<h1><%= t 'users.new.title' %></h1>

<%= render 'form' %>

<%= link_to t('links.back'), root_path %>

FGBook/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t '.title', user_name: @user.full_name %></h1>

<ul>
	<li><%= t '.locatino', locatino: @user.locatino %></li>
</ul>

<%= link_to t('.edit'), edit_user_path(@user) %>

<%= link_to 'Home', root_path %>